### ISSUE TITLE
bug: display non-existent functions after upgrade?

### ISSUE THREAD

**Issue by yeya24** [pyroscope-io/pyroscope#715]
We upgrade our argocd app and try to see the profile after adding a patch. We used pyroscope pull model to collect profiles but it looks like the displayed profiles are really outdated.

![image](https://user-images.githubusercontent.com/25150124/149225227-a6ec262b-4d11-4d93-8ef7-c0ba840a2183.png)

`db.(*db).ListClusters` function shouldn't exist and the stacktrace is the old version (before upgrade).

Compared with the profile I got from parca, the function name should be `db.(*db).GetClusterServersByName`.

![image](https://user-images.githubusercontent.com/25150124/149225413-b25601ed-16c3-47b7-9f72-ec63c92e0930.png)

I just don't understand why this case would happen in pyroscope?

**Comment by Rperry2174** [comment]
Hey @yeya24 thanks for reporting. Are you selecting a time period that includes when the "old code" was running _and_ when the "new code" was running? Does anything show up if you type `db.(*db).GetClusterServersByName` in the search bar?

**Comment by yeya24** [comment]
> db.(*db).GetClusterServersByName

No, I selected the latest time range so only the new code is running.

That's the result of search `db.(*db).GetClusterServersByName`. It is not here.

![image](https://user-images.githubusercontent.com/25150124/149233753-5948f21a-c501-49e3-bcd9-0c314b46a4dc.png)

**Comment by yeya24** [comment]
@Rperry2174 I just checked and found one more thing. We switch the namespace of that app and the app is running on `gitops-argocd` namespace now.

If I switch the namespace to the current namespace, then I can see the correct flamegraph.
![image](https://user-images.githubusercontent.com/25150124/149234631-49050daa-dc4c-490e-a2a8-09ebf5b227d8.png)

But if I don't specify the namespace tag, then the flamegraph changes back to the old one. Why is the case? The app is only running on `gitops-argocd` namespace so I assume I should see the same flamegraph whether specifying the namespace tag or not. 

![image](https://user-images.githubusercontent.com/25150124/149234821-be09e67e-0800-43ab-a267-5a0ac9d948e0.png)

Let me know whether this makes sense to you or not. And thanks for the quick help!

**Comment by Rperry2174** [comment]
@yeya24 yeah this is slightly suspicious... I'll look into it to see if I can reproduce. Just want to clarify two things:

1. There are no pods that are running outside of `gitops-argocd` namespace (you could even try adding a `namespace!="gitops-argocd"` to confirm that there is nothing outside of that namespace
2. That the new function does not exist in the second screenshot (where there are no tags selected)

**Comment by yeya24** [comment]
> * There are no pods that are running outside of `gitops-argocd` namespace (you could even try adding a `namespace!="gitops-argocd"` to confirm that there is nothing outside of that namespace
> * That the new function does not exist in the second screenshot (where there are no tags selected)

1. Yes I can confirm this. But pyroscope can still query flamegraph even if I set `namespace!="gitops-argocd"`
![image](https://user-images.githubusercontent.com/25150124/149243494-bdd36091-c5c0-48b1-a5f9-e875f05ed815.png)

2. That's true.

**Comment by kolesnikovae** [comment]
Hi @yeya24 thank you for filing the issue! It definitely makes sense and I'd like to sort it out. I also find it suspicious that the timeline is almost empty, but that's another story.

 1. Can we take a look at the k8s discovery configuration? Is it possible to adjust the config to filter out namespaces other than `gitops-argocd` from scraping?

```yaml
kubernetes-sd-configs:
  - role: pod
    # Optional namespace discovery. If omitted, all namespaces are used.
    namespaces:
      names:
        [ - <string> ]
```

 2. I'm also wondering what namespace label values you see in the dropdown list in Pyroscope UI and what it shows when you pick the old namespace.
 3. Just to confirm: if no namespace is specified, the flamegraph does not contain the new function (`db.(*db).GetClusterServersByName`), right? I'm asking because this is the most confusing thing: even if the old and new version of `argo-application-controller` were running and scraped simultaneously, the flamegraph should represent the merge of the profiles, so both functions should be shown if no query filters provided.

This is the case where #592 would be very helpful.

**Comment by yeya24** [comment]
> Can we take a look at the k8s discovery configuration? Is it possible to adjust the config to filter out namespaces other than gitops-argocd from scraping?

Yes, I definitely configured only one namespace that is `gitops-argocd` for the pull config.

> I'm also wondering what namespace label values you see in the dropdown list in Pyroscope UI and what it shows when you pick the old namespace.

I can see 2 ns.  But I don't think I have pods running on another namespace. Also the time range is latest so I expect to see only one.

![image](https://user-images.githubusercontent.com/25150124/149380789-e8c154d7-c486-4b6e-acbc-fe299d748eb7.png)

> Just to confirm: if no namespace is specified, the flamegraph does not contain the new function (db.(*db).GetClusterServersByName), right? I'm asking because this is the most confusing thing: even if the old and new version of argo-application-controller were running and scraped simultaneously, the flamegraph should represent the merge of the profiles, so both functions should be shown if no query filters provided.

That's true. It is confusing to me as well.

**Comment by kolesnikovae** [comment]
Thank you for the quick response!

> I can see 2 ns. But I don't think I have pods running on another namespace. Also the time range is latest so I expect to see only one.

Does `argocd-application-controller.cpu{namespace="infra-argocd"}` query return any data for, say, last 5 minutes?

I'll give it a closer look tomorrow, I'm still trying to reproduce it.

**Comment by yeya24** [comment]
>  Does argocd-application-controller.cpu{namespace="infra-argocd"} query return any data for, say, last 5 minutes?

![image](https://user-images.githubusercontent.com/25150124/149402849-40f9d5ba-be1b-4f5c-a1a8-f1cf0d8f367d.png)

**Comment by kolesnikovae** [comment]
@yeya24 Unfortunately, I couldn't reproduce the problem. I have some ideas but I do need more information and a sample to make sure the issue is fixed – I've instrumented the code that can potentially cause this effect: https://github.com/pyroscope-io/pyroscope/pull/731. Once it will be merged I'll ask you to collect the trace. Thank you for your help!

**Comment by kolesnikovae** [comment]
@yeya24 we've released [v0.7.2](https://github.com/pyroscope-io/pyroscope/releases/tag/v0.7.2) with pprof tracing enabled. The trace can be collected via the default `/debug/pprof/trace` endpoint:
1. Ensure pyroscope server is running and pprof endpoint is enabled (by default).
2. Start tracing (substitute URL as appropriate) - note that the duration is limited to 15s (we use 10 as it should be enough in most cases):
```
curl "http://localhost:4040/debug/pprof/trace?seconds=10" -o /tmp/trace
```
3. Execute the query of interest via UI/API.
4. Open collected trace with `go tool trace`:
```
go tool trace -http=localhost:7532 /tmp/trace
```
5. Navigate to the opened page, **User-defined tasks**, **storage.Get**.

**Comment by yeya24** [comment]
[trace.zip](https://github.com/pyroscope-io/pyroscope/files/7875875/trace.zip)
@kolesnikovae Thanks for the detailed guide. That's the trace file I got.

**Comment by kolesnikovae** [comment]
@yeya24 Thank you for the traces! I found a bug in the downsampling logic and prepared the fix: https://github.com/pyroscope-io/pyroscope/pull/737. I hope it will be merged by tomorrow.

**Comment by petethepig** [comment]
Hey @yeya24, as Anton mentioned, we prepared a fix in #737, but it will take some time for it to make it into a release, so if you want to give it a try now, I published a patched version on dockerhub, you can try it out to see if the issue is still there, here's the image name: [pyroscope/pyroscope-dev:yeya24-patch-c0de859b91fb32b059f32dc8ba02db29aed96185](https://hub.docker.com/layers/pyroscope/pyroscope-dev/yeya24-patch-c0de859b91fb32b059f32dc8ba02db29aed96185/images/sha256-f4fa5e67c5f2cfcefabd871c1e504617544cf98e15e06f1494b5fbb7fe040d30?context=explore)

Let us know how it goes!

**Comment by yeya24** [comment]
Same issue still here. I can still see the old method as well as the old tags.

**Comment by kolesnikovae** [comment]
@yeya24 thank you for your help! And I'm terribly sorry for the inconvenience. Seems to be a false trail, but more deep testing has already revealed some more issues.

Can we take a look at the new trace?

**Comment by yeya24** [comment]
> @yeya24 Oh, and it would be very helpful to take a look at the configuration - I'm particularly interested if `retention` and/or `retention-levels` are specified and if they were changed over the time.

Retention is set to 4h. Never changed since the beginning.

**Comment by kolesnikovae** [comment]
I’m puzzled that the fix doesn’t help. I think it will be more efficient if we take a look into the data.Could you please export and send us the segment that causes the problem? It does not contain any sensitive info and profiling data, just a piece of index data.
```
curl --fail -G -o /tmp/segment --data-urlencode “k=s:argocd-application-controller.cpu{app_kubernetes_io_component=application-controller,app_kubernetes_io_instance=argocd,app_kubernetes_io_managed_by=Helm,app_kubernetes_io_name=argocd-application-controller,app_kubernetes_io_part_of=argocd,app_kubernetes_io_version=d26d2bcbeedb62b05a438c87ec255edf36f726cb,container=application-controller,instance=172.24.1.178:8082,job=argocd,namespace=infra-argocd,pod=argocd-application-controller-3}” http://localhost:4040/debug/storage/export/segments
```

**Comment by kolesnikovae** [comment]
Okay, [v0.8.0](https://github.com/pyroscope-io/pyroscope/releases/tag/v0.8.0) released and we can take a look at the data. Could you please export and send us the segment that causes the problem?

```
curl --fail -G -o /tmp/segment --data-urlencode "k=s:argocd-application-controller.cpu{app_kubernetes_io_component=application-controller,app_kubernetes_io_instance=argocd,app_kubernetes_io_managed_by=Helm,app_kubernetes_io_name=argocd-application-controller,app_kubernetes_io_part_of=argocd,app_kubernetes_io_version=d26d2bcbeedb62b05a438c87ec255edf36f726cb,container=application-controller,instance=172.24.1.178:8082,job=argocd,namespace=infra-argocd,pod=argocd-application-controller-3}" http://localhost:4040/debug/storage/export/segments
```
(It targets localhost, you may need to adjust the URL.)

The segment does not contain any sensitive info and profiling data, just a piece of the index.

**Comment by yeya24** [comment]
[segment.zip](https://github.com/pyroscope-io/pyroscope/files/7944360/segment.zip)

@kolesnikovae Here's the zip for the segment file

**Comment by kolesnikovae** [comment]
I'm sorry for the delay in response. I confirm that with the sample data the issue is not reproduced in https://github.com/pyroscope-io/pyroscope/pull/737. But can be reproduced easily with the latest release.

We've added a bunch of tests, including randomised one, fixed one more related issue, and I hope this is the last time I'm asking you to test a dev build 🙏🏻 pyroscope/pyroscope-dev:git-b623c3530ddf7d0c75ad179e87b8c2030a8ae328 (tip of the https://github.com/pyroscope-io/pyroscope/pull/737)

**Comment by yeya24** [comment]
![image](https://user-images.githubusercontent.com/25150124/151640923-a35dacc8-3b63-4088-bd74-92a490a82759.png)

Thanks @kolesnikovae, I think it works now. But why I can still see the `infra-argocd` tag here? From my experience with Prometheus or other TSDB system, we cannot see expired tag/label if the series doesn't exist.

**Comment by Rperry2174** [comment]
Hey @yeya24 glad this worked for you! Unfortunately, while we have the functionality to delete _apps_ we haven't implemented functionality to delete _tags_. This is documented in #626 and we'll add this to the roadmap so that we can prioritize it soon!

**Comment by yeya24** [comment]
> Hey @yeya24 glad this worked for you! Unfortunately, while we have the functionality to delete _apps_ we haven't implemented functionality to delete _tags_. This is documented in #626 and we'll add this to the roadmap so that we can prioritize it soon!

As a TSDB it feels weird to see non exist tags. But overall it's another issue. Thanks all for the good work of fixing this issue.

**Comment by yeya24** [comment]
I think I hit another issue using the image `pyroscope/pyroscope-dev:git-b623c3530ddf7d0c75ad179e87b8c2030a8ae328`.

![image](https://user-images.githubusercontent.com/25150124/151685338-5f155fc9-ac09-43f4-980b-94af9ff2ebcd.png)
I cannot query profiles of controller 0. Let me know if you need any debug trace of the query.

But I can query the same series from parca. Any idea why this would happen? The pod itself is up and running the recent hour.
![image](https://user-images.githubusercontent.com/25150124/151685368-dd6d5e80-af8d-4444-a5e8-68cff437f58e.png)

**Comment by kolesnikovae** [comment]
It's interesting. We should take into account the fact that `/debug/pprof/profile` (CPU profiling) pprof endpoint [handles only one profiling session at a time](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/runtime/pprof/pprof.go;drc=refs%2Ftags%2Fgo1.17.6;l=782): I suspect that pprof responds pyroscope with "cpu profiling already in use". Thus, a pod (app instance) can't be profiled by both Parca and Pyroscope server simultaneously.

 - Are there any messages in the pyroscope server log? For debugging purposes I'd suggest setting 'debug' log level.
 - Does the problem manifest only with the given build?
 - Does the problem only affect this particular pod?
 - Are other pods being scraped with Parca?
 - Do queries against this pod for other profiling types return any data?
